{{- if .Values.oauth2Proxy.enabled -}}
{{- $jwksUri := .Values.istio.auth.jwksUri | default (printf "%s/protocol/openid-connect/certs" (trimSuffix "/" .Values.istio.auth.jwksIssuer)) -}}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: oauth2-proxy-ext-authz
  namespace: {{ .Values.istio.gateway.namespace }}
spec:
  workloadSelector:
    labels:
{{- toYaml .Values.istio.gateway.selector | nindent 6 }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            transport_api_version: V3
            http_service:
              server_uri:
                uri: http://oauth2-proxy.{{ .Values.oauth2Proxy.namespace }}.svc.cluster.local:{{ .Values.oauth2Proxy.service.port }}
                cluster: outbound|{{ .Values.oauth2Proxy.service.port }}||oauth2-proxy.{{ .Values.oauth2Proxy.namespace }}.svc.cluster.local
                timeout: 10s
              authorization_request:
                allowed_headers:
                  patterns:
                    - exact: cookie
                    - exact: authorization
                    - exact: x-forwarded-proto
                    - exact: x-forwarded-host
                    - exact: x-forwarded-uri
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: authorization
                    - exact: x-auth-request-user
                    - exact: x-auth-request-email
                    - exact: x-auth-request-preferred-username
                allowed_client_headers:
                  patterns:
                    - exact: set-cookie
                    - exact: location
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "auth.teknoir.online:443"
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.ext_authz:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
              disabled: true
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  jwtRules:
    - issuer: {{ .Values.istio.auth.jwksIssuer | quote }}
      jwksUri: {{ $jwksUri | quote }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
{{- if .Values.istio.auth.httpbin.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: httpbin-jwt
  namespace: {{ .Values.istio.auth.httpbin.namespace }}
spec:
  selector:
{{- toYaml .Values.istio.auth.httpbin.selector | nindent 4 }}
  jwtRules:
    - issuer: {{ .Values.istio.auth.jwksIssuer | quote }}
      jwksUri: {{ $jwksUri | quote }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin-require-jwt
  namespace: {{ .Values.istio.auth.httpbin.namespace }}
spec:
  selector:
{{- toYaml .Values.istio.auth.httpbin.selector | nindent 4 }}
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
{{- end }}
{{- if .Values.istio.mtls.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mtls-auth
  namespace: {{ .Values.authNamespace }}
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mtls-system
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: keycloak-istio-mtls
  namespace: {{ .Values.istio.gateway.namespace }}
spec:
  host: {{ .Values.keycloak.service.name | default (printf "%s-http" .Values.keycloak.fullnameOverride) }}.{{ .Values.authNamespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: oauth2-proxy-istio-mtls
  namespace: {{ .Values.istio.gateway.namespace }}
spec:
  host: oauth2-proxy.{{ .Values.oauth2Proxy.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}
{{- end -}}
