{{- if .Values.keycloak.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.authNamespace }}
spec:
  hosts:
    - "auth.teknoir.online"
  gateways:
    - {{ .Values.istio.gateway.namespace }}/{{ .Values.istio.gateway.name }}
  http:
    - route:
        - destination:
            host: {{ .Values.keycloak.service.name | default (printf "%s-http" .Values.keycloak.fullnameOverride) }}.{{ .Values.authNamespace }}.svc.cluster.local
            port:
              number: {{ .Values.keycloak.service.httpPort }}
{{- end -}}
