{{- if .Values.keycloak.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: keycloak-gateway
  namespace: {{ .Values.istio.gateway.namespace }}
spec:
  selector:
{{- toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "auth.teknoir.online"
      tls:
        mode: SIMPLE
        credentialName: teknoir-online-wildcard-tls
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.authNamespace }}
spec:
  hosts:
    - "auth.teknoir.online"
  gateways:
    - {{ .Values.istio.gateway.namespace }}/keycloak-gateway
  http:
    - route:
        - destination:
            host: {{ .Values.keycloak.fullnameOverride }}.{{ .Values.authNamespace }}.svc.cluster.local
            port:
              number: {{ .Values.keycloak.service.port }}
{{- end -}}
