{{- if .Values.oauth2Proxy.redis.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.oauth2Proxy.redis.host }}-pv
spec:
  capacity:
    storage: {{ .Values.oauth2Proxy.redis.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.oauth2Proxy.redis.storage.hostPath | quote }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.oauth2Proxy.redis.host }}-pvc
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.oauth2Proxy.redis.storage.size }}
  storageClassName: ""
  volumeName: {{ .Values.oauth2Proxy.redis.host }}-pv
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.oauth2Proxy.redis.host }}
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  selector:
    app: {{ .Values.oauth2Proxy.redis.host }}
  ports:
    - name: redis
      port: {{ .Values.oauth2Proxy.redis.port }}
      targetPort: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.oauth2Proxy.redis.host }}
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  serviceName: {{ .Values.oauth2Proxy.redis.host }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.oauth2Proxy.redis.host }}
  template:
    metadata:
      labels:
        app: {{ .Values.oauth2Proxy.redis.host }}
    spec:
      containers:
        - name: redis
          image: docker.io/redis:7.2-alpine
          ports:
            - name: redis
              containerPort: {{ .Values.oauth2Proxy.redis.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oauth2Proxy.redis.secretName }}
                  key: {{ .Values.oauth2Proxy.redis.passwordKey }}
          args:
            - --requirepass
            - "$(REDIS_PASSWORD)"
            - --appendonly
            - "yes"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.oauth2Proxy.redis.host }}-pvc
{{- end -}}
