apiVersion: v2
name: infra-stage-2
description: Infra stage 2 - Istio control plane
type: application
version: 0.1.22
appVersion: "0.1.0"
dependencies:
  - name: istiod
    alias: istiod
    version: ">=1.20.0 <2.0.0"
    repository: https://istio-release.storage.googleapis.com/charts
