apiVersion: v2
name: infra-stage-0
description: Infra stage 0 - cert-manager only
type: application
version: 0.1.9
appVersion: "0.1.0"
dependencies:
  - name: cert-manager
    version: ">=1.14.0 <2.0.0"
    repository: https://charts.jetstack.io
