apiVersion: v2
name: infra-stage-2b
description: Infra stage 2b - Istio gateways and edge routing
type: application
version: 0.1.23
appVersion: "0.1.0"
dependencies:
  - name: gateway
    alias: istio-ingressgateway
    version: ">=1.20.0 <2.0.0"
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    alias: istio-egressgateway
    version: ">=1.20.0 <2.0.0"
    repository: https://istio-release.storage.googleapis.com/charts
