apiVersion: v2
name: infra-stage-3
description: Infra stage 3 - cert-manager Istio CSR integration
type: application
version: 0.1.5
appVersion: "0.1.0"
dependencies:
  - name: cert-manager-istio-csr
    alias: istio-csr
    version: ">=0.6.0 <1.0.0"
    repository: https://charts.jetstack.io
