# Default values for infra-stage-3.
istioNamespace: istio-system

istio-csr:
  app:
    certmanager:
      issuer:
        name: istio-ca
        kind: Issuer
        group: cert-manager.io
    istio:
      namespace: istio-system
