{{- if .Values.gw.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gw.name }}
  namespace: {{ .Values.gw.namespace }}
spec:
  selector:
{{- toYaml .Values.gw.selector | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
{{- range .Values.gw.hosts }}
    - {{ . | quote }}
{{- end }}
{{- if .Values.gw.httpsRedirect }}
    tls:
      httpsRedirect: true
{{- end }}
{{- if .Values.gw.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
{{- range .Values.gw.hosts }}
    - {{ . | quote }}
{{- end }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.gw.tls.credentialName | quote }}
{{- end }}
{{- end -}}
