{{- if .Values.letsencrypt.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: {{ .Values.letsencrypt.email | quote }}
    server: {{ .Values.letsencrypt.server | quote }}
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - selector:
          dnsZones:
            - "teknoir.online"
        dns01:
          cloudDNS:
            project: {{ .Values.letsencrypt.cloudDNS.project | quote }}
            serviceAccountSecretRef:
              name: {{ .Values.letsencrypt.cloudDNS.serviceAccountSecretRef.name | quote }}
              key: {{ .Values.letsencrypt.cloudDNS.serviceAccountSecretRef.key | quote }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teknoir-online-wildcard
  namespace: {{ .Values.istioNamespace | default .Release.Namespace }}
spec:
  secretName: {{ .Values.letsencrypt.certificate.secretName | quote }}
  commonName: {{ .Values.letsencrypt.certificate.commonName | quote }}
  dnsNames:
{{- range .Values.letsencrypt.certificate.dnsNames }}
    - {{ . | quote }}
{{- end }}
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
{{- end -}}
